# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_pcmcirustr_wrappers", use_symbols = TRUE, package_name = "pcmcirustr")

#' @usage NULL
#' @useDynLib pcmcirustr, .registration = TRUE
NULL

run_pcmci <- function(data_array, max_lag, alpha, max_condition_set_size, max_subsets) .Call(wrap__run_pcmci, data_array, max_lag, alpha, max_condition_set_size, max_subsets)


# nolint end
